language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy"
  - "pypy3"


script:
  - pip install .
  - spam --help

matrix:
  allow_failures:
    - "nightly"

cache:
  directories:
    - $HOME/.cache/pip